apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: NodePort       # Type NodePort pour Docker Desktop
  selector:
    app: client-deployment   # Doit correspondre aux labels de votre déploiement
  ports:
    - protocol: TCP
      port: 3000       # Port interne du service
      targetPort: 3000 # Port du conteneur
      nodePort: 30002  # Port exposé sur le nœud (plage 30000-32767)