apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort # Ajoutez ce champ pour exposer le service via NodePort
  selector:
    app: mern-server # Assurez-vous que cela correspond aux labels de votre déploiement
  ports:
    - protocol: TCP
      port: 5000 # Port interne du service
      targetPort: 5000 # Port du conteneur
      nodePort: 30001 # Port exposé sur le nœud (doit être dans la plage 30000-32767)
