FROM node:20

# Définir le répertoire de travail
WORKDIR /usr/src/app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste des fichiers du projet
COPY . .

# Exposer le port 5000
EXPOSE 5000

# Lancer le serveur avec Nodemon
CMD ["npm", "start"]
