replicaCount: 3
image:
  repository: mouhib25/dev_mern-frontend  # Remplacez [username] par votre nom d'utilisateur Docker Hub
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
env:
  - name: REACT_APP_SERVER_URL
    value: "http://server:5000"
ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: mern-app.local
      paths:
        - path: /
  tls: []